language: node_js
node_js:
- '9'
deploy:
  provider: heroku
  api_key:
    secure: LJy9N8WgdOURCP8TB/i1VVphWBBWZlOSATJLGXb2W/sVfffKXmjzipdxNwIas+jCi/8KQd2JXuwtYPt0bqB2W49blt+0XTfUF2k8HDrx/C9MGugX51Y8txbwyDtewHo5tHlvr/mQbVuR4w4HrJhU1SanARgvP9VjfPO+TcoRjKwiW+ahS7gl+F8YrDUlBqucBb1Lr8svEZBUfbOYNAY8hn3mi1QSlY1WuPsPAmCuXN1nBTcOVbzwbQAxP5kMCfxf3/MTeg3CZ//oeM4AvpDJSnE8W5CYXLA4rE3npTd2vdyepfAqF2oi/9ZzCUkmlWpc7fBuLRiXmm0FKvVYoypY7b/x0+85IrKHXt8uaWj6FSz/SVP9uEUOKQMecJFqHpXy2Nj9g6buAdQSaMs1j4fm6eCgLI8xwR5FWAZvpWBF8VyQ6iq9645t9XDuXhtHlxGpNGB+erEaeqPVgvoAVzMCcNxrBSBBboKxaZ0FM83mpsCodjtLs1IPxumtiCCV2hywhqT4QD312jE0gT1V/xmJYa0yhEtX/SeBEiW13AH/MQqNDrAaRHkOkA4nAWvYSwGNaCuJCNTNnAYcnewwqcs+aDxCxFUr1RcgMyWIUsjHrg1gwZiHMy6seZc3J3CzMEREm+QwArckar63xFzeLaumhvUPmrrk/JQqQjk0fN4aLHo=
  app:
    master: miteb-backend-stage
    prod: miteb-backend-prod
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|prod$"
git:
  depth: 3
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/981c11c12f51d5cbb07e
    on_success: always
    on_failure: always
